export type EquipmentEntry = {
  id: string;
  name: string;
  section: 'outil' | 'aventure' | 'monture' | 'vehicule' | 'service';
  group: string;
  price: number;
  weight: number;
  desc: string;
  consumable?: boolean;
  heal?: boolean;
  uses?: number;
  capacity?: string;
  service?: boolean;
  actionSlot?: 'action' | 'bonus' | 'reaction';
};

const item = (
  id: string,
  name: string,
  section: EquipmentEntry['section'],
  group: string,
  price: number,
  weight: number,
  desc: string,
  extra: Partial<EquipmentEntry> = {},
): EquipmentEntry => ({ id, name, section, group, price, weight, desc, ...extra });

// Les prix sont exprimés en pièces d'or ; 1 pa = 0,1 po et 1 pc = 0,01 po.
export const TOOLS_CATALOG: EquipmentEntry[] = [
  item('outil-alchimiste', "Matériel d’alchimiste", 'outil', 'Outils d’artisan', 50, 3.6, 'INT · identifier une substance ou allumer un feu. Fabrique acide, feu grégeois, huile, papier et parfum.'),
  item('outil-brasseur', 'Matériel de brasseur', 'outil', 'Outils d’artisan', 20, 4.1, 'INT · détecter une boisson empoisonnée ou identifier un alcool. Fabrique de l’antitoxine.'),
  item('outil-calligraphe', 'Matériel de calligraphe', 'outil', 'Outils d’artisan', 10, 2.3, 'DEX · produire un texte difficile à contrefaire. Fabrique encre et parchemins de sort.'),
  item('outil-charpentier', 'Outils de charpentier', 'outil', 'Outils d’artisan', 8, 2.7, 'FOR · fermer ou forcer une porte ou un contenant. Travaille les objets en bois.'),
  item('outil-cartographe', 'Outils de cartographe', 'outil', 'Outils d’artisan', 15, 2.7, 'SAG · dresser la carte d’une petite zone.'),
  item('outil-cordonnier', 'Outils de cordonnier', 'outil', 'Outils d’artisan', 5, 2.3, 'DEX · adapter des chaussures pour avantager un prochain test d’Acrobaties. Fabrique le matériel d’escalade.'),
  item('outil-cuisinier', 'Ustensiles de cuisinier', 'outil', 'Outils d’artisan', 1, 3.6, 'SAG · améliorer un repas ou repérer une nourriture avariée ou empoisonnée. Fabrique des rations.'),
  item('outil-souffleur', 'Outils de souffleur de verre', 'outil', 'Outils d’artisan', 30, 2.3, 'INT · examiner les traces récentes d’un récipient en verre. Fabrique bouteilles, fioles, loupes et longues-vues.'),
  item('outil-joaillier', 'Outils de joaillier', 'outil', 'Outils d’artisan', 25, 0.9, 'INT · estimer une gemme. Fabrique des focaliseurs arcaniques et symboles sacrés.'),
  item('outil-tanneur', 'Outils de tanneur', 'outil', 'Outils d’artisan', 5, 2.3, 'DEX · décorer et travailler le cuir. Fabrique armures légères, sacs, étuis, parchemin et fouet.'),
  item('outil-macon', 'Outils de maçon', 'outil', 'Outils d’artisan', 10, 3.6, 'FOR · tailler un signe ou un trou dans la pierre. Fabrique poulie et palan.'),
  item('outil-peintre', 'Matériel de peintre', 'outil', 'Outils d’artisan', 10, 2.3, 'SAG · peindre fidèlement une scène observée. Fabrique certains focaliseurs et symboles sacrés.'),
  item('outil-potier', 'Outils de potier', 'outil', 'Outils d’artisan', 10, 1.4, 'INT · examiner les traces récentes d’un objet en céramique. Fabrique cruches et lampes.'),
  item('outil-forgeron', 'Outils de forgeron', 'outil', 'Outils d’artisan', 20, 3.6, 'FOR · forcer un accès. Fabrique la plupart des armes de mêlée, armures métalliques et objets en fer.'),
  item('outil-retameur', 'Outils de rétameur', 'outil', 'Outils d’artisan', 50, 4.5, 'DEX · assembler provisoirement un minuscule objet. Fabrique armes à feu, lanternes, pièges, cadenas et menus objets métalliques.'),
  item('outil-tisserand', 'Outils de tisserand', 'outil', 'Outils d’artisan', 1, 2.3, 'DEX · repriser ou broder. Fabrique armure matelassée, couchage, vêtements, filets, corde et tente.'),
  item('outil-sculpteur', 'Outils de sculpteur sur bois', 'outil', 'Outils d’artisan', 1, 2.3, 'DEX · graver le bois. Fabrique arcs, arbalètes, munitions, bâtons et focaliseurs en bois.'),
  item('outil-deguisement', 'Trousse de déguisement', 'outil', 'Autres outils', 25, 1.4, 'CHA · appliquer un maquillage crédible. Fabrique des costumes.'),
  item('outil-contrefacon', 'Matériel de contrefaçon', 'outil', 'Autres outils', 15, 2.3, 'DEX · imiter une courte écriture ou reproduire un sceau de cire.'),
  item('outil-herboriste', "Nécessaire d’herboriste", 'outil', 'Autres outils', 5, 1.4, 'INT · identifier une plante. Fabrique antitoxine, bougie, trousse de soins et potion de soins.'),
  item('outil-navigateur', 'Outils de navigateur', 'outil', 'Autres outils', 25, 0.9, 'SAG · tracer un cap ou déterminer sa position grâce aux étoiles.'),
  item('outil-empoisonneur', 'Matériel d’empoisonneur', 'outil', 'Autres outils', 50, 0.9, 'INT · détecter un objet empoisonné. Fabrique du poison simple.'),
  item('outil-voleur', 'Outils de voleur', 'outil', 'Autres outils', 25, 0.45, 'DEX · crocheter une serrure ou désamorcer un piège.'),
  item('jeu-des', 'Jeu de dés', 'outil', 'Jeux', 0.1, 0, 'SAG · repérer une tricherie ou remporter une partie.'),
  item('jeu-echecs', 'Jeu d’échecs draconiques', 'outil', 'Jeux', 1, 0, 'SAG · repérer une tricherie ou remporter une partie.'),
  item('jeu-cartes', 'Jeu de cartes', 'outil', 'Jeux', 0.5, 0, 'SAG · repérer une tricherie ou remporter une partie.'),
  item('jeu-trois-dragons', 'Jeu des Trois Dragons', 'outil', 'Jeux', 1, 0, 'SAG · repérer une tricherie ou remporter une partie.'),
  item('instrument-cornemuse', 'Cornemuse', 'outil', 'Instruments', 30, 2.7, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-tambour', 'Tambour', 'outil', 'Instruments', 6, 1.4, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-tympanon', 'Tympanon', 'outil', 'Instruments', 25, 4.5, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-flute', 'Flûte', 'outil', 'Instruments', 2, 0.45, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-cor', 'Cor', 'outil', 'Instruments', 3, 0.9, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-luth', 'Luth', 'outil', 'Instruments', 35, 0.9, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-lyre', 'Lyre', 'outil', 'Instruments', 30, 0.9, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-flute-pan', 'Flûte de Pan', 'outil', 'Instruments', 12, 0.9, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-chalemie', 'Chalemie', 'outil', 'Instruments', 2, 0.45, 'CHA · jouer un air connu ou improviser.'),
  item('instrument-viole', 'Viole', 'outil', 'Instruments', 30, 0.45, 'CHA · jouer un air connu ou improviser.'),
];

export const ADVENTURING_GEAR: EquipmentEntry[] = [
  item('av-acide', 'Acide', 'aventure', 'Alchimie', 25, 0.45, 'Remplace une attaque : cible à 6 m, sauvegarde de DEX ou 2d6 dégâts d’acide.', { consumable: true, actionSlot: 'action' }),
  item('av-feu-gregeois', 'Feu grégeois', 'aventure', 'Alchimie', 50, 0.45, 'Remplace une attaque : cible à 6 m, sauvegarde de DEX ou 1d4 feu et Brûle.', { consumable: true, actionSlot: 'action' }),
  item('mun-fleches', 'Flèches (20)', 'aventure', 'Munitions', 1, 0.45, 'Munitions d’arc ; un carquois en contient 20.', { consumable: true, uses: 20 }),
  item('mun-carreaux', 'Carreaux (20)', 'aventure', 'Munitions', 1, 0.7, 'Munitions d’arbalète ; un étui en contient 20.', { consumable: true, uses: 20 }),
  item('mun-balles-feu', 'Balles d’arme à feu (10)', 'aventure', 'Munitions', 3, 0.9, 'Munitions de mousquet ou de pistolet.', { consumable: true, uses: 10 }),
  item('mun-billes-fronde', 'Billes de fronde (20)', 'aventure', 'Munitions', 0.04, 0.7, 'Munitions de fronde.', { consumable: true, uses: 20 }),
  item('mun-aiguilles', 'Aiguilles de sarbacane (50)', 'aventure', 'Munitions', 1, 0.45, 'Munitions de sarbacane.', { consumable: true, uses: 50 }),
  item('av-antitoxine', 'Antitoxine', 'aventure', 'Alchimie', 50, 0, 'Action bonus : avantage pendant 1 heure contre l’état Empoisonné.', { consumable: true, actionSlot: 'bonus' }),
  item('focus-cristal', 'Cristal arcanique', 'aventure', 'Focaliseurs', 10, 0.45, 'Focaliseur arcanique tenu.'),
  item('focus-orbe', 'Orbe arcanique', 'aventure', 'Focaliseurs', 20, 1.4, 'Focaliseur arcanique tenu.'),
  item('focus-baguette', 'Baguette arcanique', 'aventure', 'Focaliseurs', 10, 0.45, 'Focaliseur arcanique tenu.'),
  item('focus-baton', 'Bâton arcanique', 'aventure', 'Focaliseurs', 5, 1.8, 'Focaliseur arcanique utilisable comme bâton de combat.'),
  item('focus-sceptre', 'Sceptre arcanique', 'aventure', 'Focaliseurs', 10, 0.9, 'Focaliseur arcanique tenu.'),
  item('av-sac-dos', 'Sac à dos', 'aventure', 'Contenants', 2, 2.3, 'Contient jusqu’à 13,5 kg dans environ 28 litres.', { capacity: '13,5 kg' }),
  item('av-billes', 'Billes', 'aventure', 'Terrain', 1, 0.9, 'Action Utiliser : couvre un carré de 3 m ; sauvegarde de DEX DD 10 ou À terre.'),
  item('av-tonneau', 'Tonneau', 'aventure', 'Contenants', 2, 31.8, 'Contient environ 150 litres de liquide ou 113 litres de matière sèche.'),
  item('av-panier', 'Panier', 'aventure', 'Contenants', 0.4, 0.9, 'Contient jusqu’à 18 kg.'),
  item('av-sac-couchage', 'Sac de couchage', 'aventure', 'Voyage', 1, 3.2, 'Protège une créature P ou M et sécurise contre le froid extrême pendant le sommeil.'),
  item('av-clochette', 'Clochette', 'aventure', 'Utilitaire', 1, 0, 'Action Utiliser : audible jusqu’à 18 m.'),
  item('av-couverture', 'Couverture', 'aventure', 'Voyage', 0.5, 1.4, 'Avantage aux sauvegardes contre le froid extrême quand elle enveloppe le personnage.'),
  item('av-palan', 'Poulie et palan', 'aventure', 'Utilitaire', 1, 2.3, 'Permet de hisser quatre fois le poids normalement soulevable.'),
  item('av-livre', 'Livre', 'aventure', 'Savoir', 25, 2.3, 'Un ouvrage exact donne +5 à certains tests d’INT sur son sujet.'),
  item('av-bouteille', 'Bouteille en verre', 'aventure', 'Contenants', 2, 0.9, 'Contient environ 0,75 litre.'),
  item('av-seau', 'Seau', 'aventure', 'Contenants', 0.05, 0.9, 'Contient environ 14 litres.'),
  item('pack-cambrioleur', 'Sacoche de cambrioleur', 'aventure', 'Paquets', 16, 19.1, 'Sac à dos, billes, clochette, bougies, pied-de-biche, lanterne, huile, rations, corde, briquet et outre.'),
  item('av-chaussetrappes', 'Chausse-trappes', 'aventure', 'Terrain', 1, 0.9, 'Action Utiliser : couvre 1,50 m ; sauvegarde de DEX DD 15 ou 1 perforant et vitesse 0 jusqu’au prochain tour.'),
  item('av-bougie', 'Bougie', 'aventure', 'Éclairage', 0.01, 0, 'Brûle 1 heure ; lumière vive à 1,50 m et faible 1,50 m plus loin.', { consumable: true }),
  item('av-etui-carreaux', 'Étui à carreaux', 'aventure', 'Contenants', 1, 0.45, 'Contient jusqu’à 20 carreaux.'),
  item('av-etui-cartes', 'Étui à cartes ou parchemins', 'aventure', 'Contenants', 1, 0.45, 'Contient dix feuilles de papier ou cinq parchemins.'),
  item('av-chaine', 'Chaîne', 'aventure', 'Entrave', 5, 4.5, 'Peut entraver une cible déjà agrippée, neutralisée ou entravée ; tests prévus pour poser et s’échapper.'),
  item('av-coffre', 'Coffre', 'aventure', 'Contenants', 5, 11.3, 'Contient environ 340 litres.'),
  item('av-escalade', 'Matériel d’escalade', 'aventure', 'Voyage', 25, 5.4, 'Action Utiliser : s’ancrer et limiter une chute ou l’éloignement à 7,50 m.'),
  item('av-tenue-luxe', 'Tenue raffinée', 'aventure', 'Vêtements', 15, 2.7, 'Tenue de qualité exigée dans certains lieux et événements.'),
  item('av-tenue-voyage', 'Tenue de voyage', 'aventure', 'Vêtements', 2, 1.8, 'Vêtements solides adaptés au voyage.'),
  item('av-sacoche-composantes', 'Sacoche à composantes', 'aventure', 'Focaliseurs', 25, 0.9, 'Contient les composantes matérielles sans prix indiqué et non consommées.'),
  item('av-costume', 'Costume', 'aventure', 'Vêtements', 5, 1.8, 'Avantage aux tests pour imiter le personnage ou le type représenté.'),
  item('av-pied-biche', 'Pied-de-biche', 'aventure', 'Utilitaire', 2, 2.3, 'Avantage aux tests de Force où son levier s’applique.'),
  item('pack-diplomate', 'Sacoche de diplomate', 'aventure', 'Paquets', 39, 17.7, 'Coffre, tenue raffinée, écriture, lampe, étuis, huile, papier, parchemin, parfum et briquet.'),
  item('focus-gui', 'Brin de gui', 'aventure', 'Focaliseurs', 1, 0, 'Focaliseur druidique.'),
  item('focus-bois', 'Bâton druidique', 'aventure', 'Focaliseurs', 5, 1.8, 'Focaliseur druidique utilisable comme bâton de combat.'),
  item('focus-if', 'Baguette d’if', 'aventure', 'Focaliseurs', 10, 0.45, 'Focaliseur druidique.'),
  item('pack-exploration-souterraine', 'Sacoche d’exploration souterraine', 'aventure', 'Paquets', 12, 25, 'Sac à dos, chausse-trappes, pied-de-biche, huile, rations, corde, briquet, torches et outre.'),
  item('pack-artiste', 'Sacoche d’artiste', 'aventure', 'Paquets', 40, 26.5, 'Sac à dos, couchage, clochette, lanterne, costumes, miroir, huile, rations, briquet et outre.'),
  item('pack-explorateur', 'Sacoche d’explorateur', 'aventure', 'Paquets', 10, 25, 'Sac à dos, couchage, huile, rations, corde, briquet, torches et outre.'),
  item('av-flasque', 'Flasque', 'aventure', 'Contenants', 0.02, 0.45, 'Contient environ un demi-litre.'),
  item('av-grappin', 'Grappin', 'aventure', 'Utilitaire', 2, 1.8, 'Action Utiliser : accrocher à 15 m avec un test d’Acrobaties DD 13.'),
  item('av-trousse-soins', 'Trousse de soins', 'aventure', 'Soins', 5, 1.4, 'Dix utilisations ; une action stabilise une créature inconsciente à 0 PV sans test.', { uses: 10 }),
  item('symbole-amulette', 'Symbole sacré · amulette', 'aventure', 'Focaliseurs', 5, 0.45, 'Focaliseur divin porté ou tenu.'),
  item('symbole-embleme', 'Symbole sacré · emblème', 'aventure', 'Focaliseurs', 5, 0, 'Focaliseur divin apposé sur un tissu ou un bouclier.'),
  item('symbole-reliquaire', 'Symbole sacré · reliquaire', 'aventure', 'Focaliseurs', 5, 0.9, 'Focaliseur divin tenu.'),
  item('av-eau-benite', 'Eau bénite', 'aventure', 'Alchimie', 25, 0.45, 'Remplace une attaque : cible à 6 m ; un fiélon ou mort-vivant rate sa sauvegarde de DEX et subit 2d8 radiants.', { consumable: true, actionSlot: 'action' }),
  item('av-piege-chasse', 'Piège de chasse', 'aventure', 'Terrain', 5, 11.3, 'Action Utiliser : sauvegarde de DEX DD 13 ou 1d4 perforant et vitesse 0, puis entrave par sa chaîne.'),
  item('av-encre', 'Encre', 'aventure', 'Écriture', 10, 0, 'Une bouteille permet d’écrire environ 500 pages.'),
  item('av-plume', 'Plume à encre', 'aventure', 'Écriture', 0.02, 0, 'Permet d’écrire ou dessiner avec de l’encre.'),
  item('av-cruche', 'Cruche', 'aventure', 'Contenants', 0.02, 1.8, 'Contient environ 3,8 litres.'),
  item('av-echelle', 'Échelle', 'aventure', 'Utilitaire', 0.1, 11.3, 'Échelle de 3 m.'),
  item('av-lampe', 'Lampe', 'aventure', 'Éclairage', 0.5, 0.45, 'Huile : lumière vive à 4,50 m, faible 9 m plus loin.'),
  item('av-lanterne-faisceau', 'Lanterne à faisceau', 'aventure', 'Éclairage', 10, 0.9, 'Huile : cône de lumière vive de 18 m puis faible sur 18 m.'),
  item('av-lanterne-capote', 'Lanterne à capote', 'aventure', 'Éclairage', 5, 0.9, 'Huile : lumière vive à 9 m puis faible 9 m ; la capote réduit à 1,50 m de lumière faible.'),
  item('av-cadenas', 'Cadenas', 'aventure', 'Utilitaire', 10, 0.45, 'Fourni avec une clé ; crochetage avec outils de voleur, DEX DD 15.'),
  item('av-loupe', 'Loupe', 'aventure', 'Utilitaire', 100, 0, 'Avantage pour estimer ou inspecter un objet très détaillé.'),
  item('av-menottes', 'Menottes', 'aventure', 'Entrave', 2, 2.7, 'Entrave une cible P ou M déjà agrippée, neutralisée ou entravée ; résistance et crochetage prévus.'),
  item('av-carte', 'Carte', 'aventure', 'Savoir', 1, 0, 'Une carte exacte donne +5 aux tests de Survie pour s’orienter dans la zone représentée.'),
  item('av-miroir', 'Miroir', 'aventure', 'Utilitaire', 5, 0.23, 'Miroir d’acier utilisable pour observer un angle ou envoyer un signal lumineux.'),
  item('av-filet', 'Filet', 'aventure', 'Combat', 1, 1.4, 'Remplace une attaque à 4,50 m : sauvegarde de DEX ou Entravé ; inefficace sur une cible TG ou plus.'),
  item('av-huile', 'Huile', 'aventure', 'Alchimie', 0.1, 0.45, 'Asperge une cible ou une zone et renforce les dégâts de feu ; alimente lampe ou lanterne pendant 6 heures.', { consumable: true, actionSlot: 'action' }),
  item('av-papier', 'Papier', 'aventure', 'Écriture', 0.2, 0, 'Une feuille reçoit environ 250 mots manuscrits.', { consumable: true }),
  item('av-parchemin', 'Parchemin', 'aventure', 'Écriture', 0.1, 0, 'Une feuille reçoit environ 250 mots manuscrits.', { consumable: true }),
  item('av-parfum', 'Parfum', 'aventure', 'Social', 5, 0, 'Pendant 1 heure, avantage en Persuasion pour influencer un humanoïde Indifférent adjacent.', { consumable: true }),
  item('av-poison', 'Poison simple', 'aventure', 'Alchimie', 100, 0, 'Action bonus : enduit une arme ou trois munitions ; prochain impact ajoute 1d4 poison pendant 1 minute.', { consumable: true, actionSlot: 'bonus' }),
  item('av-perche', 'Perche', 'aventure', 'Utilitaire', 0.05, 3.2, 'Perche de 3 m ; avantage pour un saut en hauteur ou en longueur avec élan à la perche.'),
  item('av-marmite', 'Marmite en fer', 'aventure', 'Contenants', 2, 4.5, 'Contient environ 3,8 litres.'),
  item('av-potion-soins', 'Potion de soins', 'aventure', 'Soins', 50, 0.23, 'Action bonus : une créature adjacente récupère 2d4 + 2 PV.', { consumable: true, heal: true, actionSlot: 'bonus' }),
  item('av-sacoche', 'Sacoche', 'aventure', 'Contenants', 0.5, 0.45, 'Contient jusqu’à 2,7 kg.', { capacity: '2,7 kg' }),
  item('pack-pretre', 'Sacoche de prêtre', 'aventure', 'Paquets', 33, 13.2, 'Sac à dos, couverture, eau bénite, lampe, rations, robe et briquet.'),
  item('av-carquois', 'Carquois', 'aventure', 'Contenants', 1, 0.45, 'Contient jusqu’à 20 flèches.'),
  item('av-belier', 'Bélier portable', 'aventure', 'Utilitaire', 4, 15.9, '+4 aux tests de Force pour enfoncer une porte ; un allié peut aider et donner l’avantage.'),
  item('av-rations', 'Rations (1 jour)', 'aventure', 'Voyage', 0.5, 0.9, 'Nourriture de voyage pour une journée.', { consumable: true }),
  item('av-robe', 'Robe', 'aventure', 'Vêtements', 1, 1.8, 'Vêtement à portée professionnelle ou cérémonielle.'),
  item('av-corde', 'Corde (15 m)', 'aventure', 'Utilitaire', 1, 2.3, 'Nouer avec Escamotage DD 10 ; rompre avec Athlétisme DD 20 ; peut entraver une cible déjà maîtrisée.'),
  item('av-sac', 'Sac', 'aventure', 'Contenants', 0.01, 0.23, 'Contient jusqu’à 13,5 kg.', { capacity: '13,5 kg' }),
  item('pack-erudit', 'Sacoche d’érudit', 'aventure', 'Paquets', 40, 10, 'Sac à dos, livre, encre, plume, lampe, huile, parchemin et briquet.'),
  item('av-pelle', 'Pelle', 'aventure', 'Utilitaire', 2, 2.3, 'Creuse en une heure un trou de 1,50 m de côté dans un sol meuble.'),
  item('av-sifflet', 'Sifflet', 'aventure', 'Utilitaire', 0.05, 0, 'Action Utiliser : audible jusqu’à 180 m.'),
  item('av-parchemin-mineur', 'Parchemin de sort mineur', 'aventure', 'Magie', 30, 0, 'Lance le sort inscrit s’il figure sur ta liste ; DD 13 et attaque +5.', { consumable: true }),
  item('av-parchemin-n1', 'Parchemin de sort niveau 1', 'aventure', 'Magie', 50, 0, 'Lance le sort inscrit s’il figure sur ta liste ; DD 13 et attaque +5.', { consumable: true }),
  item('av-pitons', 'Pointes en fer (10)', 'aventure', 'Utilitaire', 1, 2.3, 'Se plantent dans le bois, la terre ou un matériau semblable pour bloquer une porte ou fixer une corde.'),
  item('av-longue-vue', 'Longue-vue', 'aventure', 'Utilitaire', 1000, 0.45, 'Les objets observés paraissent deux fois plus grands.'),
  item('av-ficelle', 'Ficelle (3 m)', 'aventure', 'Utilitaire', 0.1, 0, 'Ficelle de 3 m ; faire un nœud demande l’action Utiliser.'),
  item('av-tente', 'Tente', 'aventure', 'Voyage', 2, 9.1, 'Abrite jusqu’à deux créatures P ou M.'),
  item('av-briquet', 'Briquet à amadou', 'aventure', 'Utilitaire', 0.5, 0.45, 'Action bonus pour une flamme à combustible exposé ; sinon une minute.'),
  item('av-torche', 'Torche', 'aventure', 'Éclairage', 0.01, 0.45, 'Brûle 1 heure ; lumière vive à 6 m et faible 6 m plus loin ; arme improvisée à 1 dégât de feu.', { consumable: true }),
  item('av-fiole', 'Fiole', 'aventure', 'Contenants', 1, 0, 'Contient environ 12 cl.'),
  item('av-outre', 'Outre', 'aventure', 'Voyage', 0.2, 2.3, 'Contient environ 1,9 litre ; poids indiqué pleine.'),
];

export const MOUNTS_AND_VEHICLES: EquipmentEntry[] = [
  item('monture-chameau', 'Chameau', 'monture', 'Montures', 50, 0, 'Capacité de charge : 204 kg.', { capacity: '204 kg' }),
  item('monture-elephant', 'Éléphant', 'monture', 'Montures', 200, 0, 'Capacité de charge : 599 kg.', { capacity: '599 kg' }),
  item('monture-cheval-trait', 'Cheval de trait', 'monture', 'Montures', 50, 0, 'Capacité de charge : 245 kg.', { capacity: '245 kg' }),
  item('monture-cheval-selle', 'Cheval de selle', 'monture', 'Montures', 75, 0, 'Capacité de charge : 218 kg.', { capacity: '218 kg' }),
  item('monture-molosse', 'Molosse', 'monture', 'Montures', 25, 0, 'Capacité de charge : 88 kg.', { capacity: '88 kg' }),
  item('monture-mule', 'Mule', 'monture', 'Montures', 8, 0, 'Capacité de charge : 191 kg.', { capacity: '191 kg' }),
  item('monture-poney', 'Poney', 'monture', 'Montures', 30, 0, 'Capacité de charge : 102 kg.', { capacity: '102 kg' }),
  item('monture-destrier', 'Destrier', 'monture', 'Montures', 400, 0, 'Capacité de charge : 245 kg.', { capacity: '245 kg' }),
  item('veh-carrosse', 'Carrosse', 'vehicule', 'Véhicules terrestres', 100, 272, 'Véhicule tracté.'),
  item('veh-charrette', 'Charrette', 'vehicule', 'Véhicules terrestres', 15, 91, 'Véhicule tracté.'),
  item('veh-char', 'Char', 'vehicule', 'Véhicules terrestres', 250, 45, 'Véhicule tracté.'),
  item('veh-traineau', 'Traîneau', 'vehicule', 'Véhicules terrestres', 20, 136, 'Véhicule tracté.'),
  item('veh-chariot', 'Chariot', 'vehicule', 'Véhicules terrestres', 35, 181, 'Véhicule tracté.'),
  item('selle-exotique', 'Selle exotique', 'vehicule', 'Harnachement', 60, 18, 'Requise pour une monture aquatique ou volante.'),
  item('selle-militaire', 'Selle militaire', 'vehicule', 'Harnachement', 20, 13.6, 'Avantage aux tests pour rester en selle.'),
  item('selle-equitation', 'Selle d’équitation', 'vehicule', 'Harnachement', 10, 11.3, 'Selle, mors, bride et rênes.'),
  item('veh-dirigeable', 'Dirigeable', 'vehicule', 'Grands véhicules', 40000, 0, '13 km/h · équipage 10 · 20 passagers · CA 13 · 300 PV · seuil 0.'),
  item('veh-galere', 'Galère', 'vehicule', 'Grands véhicules', 30000, 0, '6,5 km/h · équipage 80 · 150 passagers · CA 15 · 500 PV · seuil 20.'),
  item('veh-quillard', 'Quillard', 'vehicule', 'Grands véhicules', 3000, 0, '1,6 km/h · équipage 1 · 6 passagers · CA 15 · 100 PV · seuil 10.'),
  item('veh-drakkar', 'Drakkar', 'vehicule', 'Grands véhicules', 10000, 0, '4,8 km/h · équipage 40 · 150 passagers · CA 15 · 300 PV · seuil 15.'),
  item('veh-chaloupe', 'Chaloupe', 'vehicule', 'Grands véhicules', 50, 45, '2,4 km/h · équipage 1 · 3 passagers · CA 11 · 50 PV.'),
  item('veh-voilier', 'Voilier', 'vehicule', 'Grands véhicules', 10000, 0, '3,2 km/h · équipage 20 · 20 passagers · CA 15 · 300 PV · seuil 15.'),
  item('veh-navire-guerre', 'Navire de guerre', 'vehicule', 'Grands véhicules', 25000, 0, '4 km/h · équipage 60 · 60 passagers · CA 15 · 500 PV · seuil 20.'),
];

export const SERVICES_CATALOG: EquipmentEntry[] = [
  item('service-fourrage', 'Fourrage · 1 jour', 'service', 'Montures', 0.05, 4.5, 'Nourriture quotidienne d’une monture.', { service: true }),
  item('service-ecurie', 'Écurie · 1 jour', 'service', 'Montures', 0.5, 0, 'Hébergement quotidien d’une monture.', { service: true }),
  item('service-train-ville', 'Cocher en ville · 1,6 km', 'service', 'Voyage', 0.01, 0, 'Transport à l’intérieur d’une ville.', { service: true }),
  item('service-train-route', 'Cocher entre villes · 1,6 km', 'service', 'Voyage', 0.03, 0, 'Transport routier entre deux villes.', { service: true }),
  item('service-peage', 'Péage routier ou porte', 'service', 'Voyage', 0.01, 0, 'Droit de passage indicatif.', { service: true }),
  item('service-bateau', 'Passage maritime · 1,6 km', 'service', 'Voyage', 0.1, 0, 'Passage en navire ; prix indicatif par distance.', { service: true }),
  item('service-messager', 'Messager · 1,6 km', 'service', 'Services', 0.02, 0, 'Prix indicatif par distance.', { service: true }),
  item('service-journalier', 'Employé non qualifié · 1 jour', 'service', 'Services', 0.2, 0, 'Travail ne demandant aucune maîtrise particulière.', { service: true }),
  item('service-expert', 'Employé qualifié · 1 jour', 'service', 'Services', 2, 0, 'Travail demandant une maîtrise d’arme, d’outil ou de compétence.', { service: true }),
  item('service-sort-0', 'Lancement d’un sort mineur', 'service', 'Services magiques', 30, 0, 'Disponible dans un village, une ville ou une cité ; composantes coûteuses en supplément.', { service: true }),
  item('service-sort-1', 'Lancement d’un sort niveau 1', 'service', 'Services magiques', 50, 0, 'Disponible dans un village, une ville ou une cité ; composantes coûteuses en supplément.', { service: true }),
  item('service-sort-2', 'Lancement d’un sort niveau 2', 'service', 'Services magiques', 200, 0, 'Disponible dans un village, une ville ou une cité ; composantes coûteuses en supplément.', { service: true }),
  item('service-sort-3', 'Lancement d’un sort niveau 3', 'service', 'Services magiques', 300, 0, 'Disponible seulement dans une ville ou une cité.', { service: true }),
  item('service-sort-45', 'Lancement d’un sort niveau 4–5', 'service', 'Services magiques', 2000, 0, 'Disponible seulement dans une ville ou une cité.', { service: true }),
  item('service-sort-68', 'Lancement d’un sort niveau 6–8', 'service', 'Services magiques', 20000, 0, 'Disponible seulement dans une cité.', { service: true }),
  item('service-sort-9', 'Lancement d’un sort niveau 9', 'service', 'Services magiques', 100000, 0, 'Disponible seulement dans une cité.', { service: true }),
];

export const EQUIPMENT_CATALOG = [
  ...TOOLS_CATALOG,
  ...ADVENTURING_GEAR,
  ...MOUNTS_AND_VEHICLES,
  ...SERVICES_CATALOG,
];

export function formatPriceGp(price: number): string {
  const rounded = Math.round(price * 100);
  if (rounded === 0) return 'gratuit';
  if (rounded < 10) return `${rounded} pc`;
  if (rounded < 100 && rounded % 10 === 0) return `${rounded / 10} pa`;
  return `${Number((rounded / 100).toFixed(2))} po`;
}
