export type RuleCategory = 'Actions' | 'Combat' | 'Mouvement' | 'Exploration' | 'Interaction' | 'Magie' | 'Santé' | 'Repos et survie';

export type RuleEntry = {
  id: string;
  category: RuleCategory;
  title: string;
  summary: string;
  keywords: string[];
};

export const RULE_CATEGORIES: RuleCategory[] = ['Actions', 'Combat', 'Mouvement', 'Exploration', 'Interaction', 'Magie', 'Santé', 'Repos et survie'];

// Résumés originaux et volontairement opérationnels. Le scan privé sert à la
// vérification, mais aucun texte du livre n'est livré avec l'application.
export const RULES_COMPENDIUM: RuleEntry[] = [
  { id: 'action-attack', category: 'Actions', title: 'Attaquer', summary: 'Choisis une cible à portée, détermine les modificateurs et le couvert, puis résous le jet d’attaque et les dégâts. Les attaques supplémentaires appartiennent à cette même action.', keywords: ['attaque', 'arme', 'cible'] },
  { id: 'action-dash', category: 'Actions', title: 'Foncer', summary: 'Tu gagnes pour ce tour un déplacement supplémentaire égal à ta vitesse après ses modificateurs.', keywords: ['dash', 'vitesse', 'déplacement'] },
  { id: 'action-disengage', category: 'Actions', title: 'Se désengager', summary: 'Tes déplacements ne provoquent pas d’attaque d’opportunité pendant le reste du tour.', keywords: ['opportunité', 'retraite'] },
  { id: 'action-dodge', category: 'Actions', title: 'Esquiver', summary: 'Jusqu’au début de ton prochain tour, les attaques contre toi ont le désavantage et tes sauvegardes de Dextérité ont l’avantage. Le bénéfice cesse si tu es Incapable d’agir ou si ta vitesse tombe à 0.', keywords: ['dodge', 'défense', 'dextérité'] },
  { id: 'action-help', category: 'Actions', title: 'Aider', summary: 'Aide un allié proche sur un test pertinent, ou distrais un ennemi à 1,50 m pour avantager la prochaine attaque d’un allié avant ton prochain tour.', keywords: ['help', 'avantage', 'allié'] },
  { id: 'action-hide', category: 'Actions', title: 'Se cacher', summary: 'Fais un test de Dextérité (Discrétion) DD 15 en étant hors de la ligne de vue et fortement obscurci ou derrière un couvert important. Le total obtenu devient le DD pour te trouver.', keywords: ['hide', 'furtif', 'discrétion', 'invisible'] },
  { id: 'action-influence', category: 'Actions', title: 'Influencer', summary: 'Décris ta demande et ton approche. Une cible volontaire accepte, une cible opposée refuse, et une cible hésitante appelle un test social adapté à son attitude.', keywords: ['social', 'persuasion', 'intimidation', 'tromperie'] },
  { id: 'action-magic', category: 'Actions', title: 'Magie', summary: 'Cette action sert à lancer la majorité des sorts, activer certains objets magiques et employer des capacités explicitement marquées comme actions de Magie.', keywords: ['sort', 'objet magique', 'incantation'] },
  { id: 'action-ready', category: 'Actions', title: 'Préparer', summary: 'Définis un déclencheur perceptible et une action ou un déplacement. Tu pourras utiliser ta réaction après le déclencheur, avant le début de ton prochain tour. Préparer un sort demande la concentration.', keywords: ['ready', 'réaction', 'déclencheur'] },
  { id: 'action-search', category: 'Actions', title: 'Chercher', summary: 'Fais un test de Sagesse : Intuition pour l’état d’esprit, Médecine pour un mal, Perception pour ce qui est caché, Survie pour les traces ou la nourriture.', keywords: ['search', 'perception', 'intuition', 'survie'] },
  { id: 'action-study', category: 'Actions', title: 'Étudier', summary: 'Fais un test d’Intelligence avec Arcanes, Histoire, Investigation, Nature ou Religion pour rappeler ou déduire une information.', keywords: ['study', 'investigation', 'connaissance'] },
  { id: 'action-utilize', category: 'Actions', title: 'Utiliser', summary: 'Emploie cette action lorsqu’un objet non magique exige une action dédiée. Sortir ou ranger un objet peut généralement accompagner une autre action.', keywords: ['utilize', 'objet', 'interaction'] },

  { id: 'combat-initiative', category: 'Combat', title: 'Initiative et surprise', summary: 'L’initiative est un test de Dextérité. Une créature surprise commence avec le désavantage à ce jet ; les égalités entre joueurs sont tranchées par eux, les autres par le MJ.', keywords: ['ordre', 'surprise', 'dextérité'] },
  { id: 'combat-cover', category: 'Combat', title: 'Couvert', summary: 'Demi-couvert : +2 à la CA et aux sauvegardes de Dextérité. Couvert aux trois quarts : +5. Couvert total : la cible ne peut pas être visée directement. Les couverts ne se cumulent pas.', keywords: ['ca', 'dex', 'obstacle'] },
  { id: 'combat-opportunity', category: 'Combat', title: 'Attaque d’opportunité', summary: 'Quand une créature visible quitte ta portée avec son déplacement, une action, une action bonus ou une réaction, tu peux dépenser ta réaction pour l’attaquer juste avant sa sortie. Téléportation et déplacement forcé ne provoquent pas.', keywords: ['réaction', 'portée', 'déplacement'] },
  { id: 'combat-ranged', category: 'Combat', title: 'Attaque à distance', summary: 'Au-delà de la portée normale et dans la portée longue, le jet a le désavantage. Une menace hostile au contact peut aussi imposer le désavantage selon la situation.', keywords: ['arc', 'portée', 'désavantage'] },
  { id: 'combat-unseen', category: 'Combat', title: 'Attaquants et cibles invisibles', summary: 'Attaquer une cible que tu ne vois pas impose le désavantage et peut rater automatiquement si sa position est mal devinée. Une créature qui ne te voit pas t’accorde l’avantage ; attaquer révèle ta position.', keywords: ['invisible', 'caché', 'avantage'] },
  { id: 'combat-knockout', category: 'Combat', title: 'Mettre hors de combat', summary: 'Quand une attaque de corps à corps devrait réduire une créature à 0 PV, l’attaquant peut choisir de la laisser à 1 PV et Inconsciente. Des soins ou des premiers secours DD 10 peuvent la réveiller.', keywords: ['non létal', 'inconscient', 'médecine'] },
  { id: 'combat-critical', category: 'Combat', title: 'Coup critique', summary: 'Un 20 naturel à une attaque touche automatiquement. Lance deux fois tous les dés de dégâts de l’attaque, y compris les dés supplémentaires applicables, puis ajoute les modificateurs une seule fois.', keywords: ['20 naturel', 'double', 'dés', 'critique'] },
  { id: 'combat-unarmed', category: 'Combat', title: 'Frappe à mains nues', summary: 'Choisis entre blesser, agripper ou bousculer une cible à 1,50 m. Blesser demande une attaque et inflige 1 + Force ; les deux autres imposent une sauvegarde de Force ou Dextérité contre 8 + maîtrise + Force.', keywords: ['poing', 'agripper', 'bousculer', 'lutte'] },
  { id: 'combat-grapple', category: 'Combat', title: 'Agripper et s’échapper', summary: 'Une main libre ne peut maintenir qu’une cible. La cible agrippée a une vitesse nulle ; elle s’échappe par une action et un test d’Athlétisme ou d’Acrobaties contre le DD de fuite. L’incapacité du grappler ou une portée rompue termine aussi l’effet.', keywords: ['aggripé', 'grapple', 'athlétisme', 'acrobaties', 'main libre'] },
  { id: 'combat-shove', category: 'Combat', title: 'Bousculer', summary: 'Une frappe à mains nues peut pousser de 1,50 m ou mettre À terre une cible d’au plus une catégorie de taille supérieure, si elle rate sa sauvegarde de Force ou Dextérité.', keywords: ['shove', 'pousser', 'à terre', 'taille'] },
  { id: 'combat-light', category: 'Combat', title: 'Deux armes légères', summary: 'Après une attaque avec une arme Légère, tu peux effectuer plus tard dans le tour une attaque supplémentaire avec une autre arme Légère, normalement en action bonus. Le modificateur de caractéristique ne s’ajoute pas à ses dégâts sauf s’il est négatif.', keywords: ['légère', 'deux armes', 'bonus'] },
  { id: 'combat-nick', category: 'Combat', title: 'Entaille et attaque légère', summary: 'La maîtrise Entaille place l’attaque supplémentaire d’une arme Légère dans l’action Attaquer au lieu de l’action bonus. Cette attaque supplémentaire reste limitée à une par tour.', keywords: ['nick', 'entaille', 'légère', 'maîtrise'] },
  { id: 'combat-mounted', category: 'Combat', title: 'Combat monté', summary: 'Monter ou descendre coûte la moitié de la vitesse. Une monture contrôlée agit pendant ton tour et se limite aux actions autorisées ; une monture indépendante conserve sa propre initiative.', keywords: ['monture', 'cheval', 'initiative', 'descendre'] },
  { id: 'combat-underwater', category: 'Combat', title: 'Combat sous l’eau', summary: 'Sans vitesse de nage, de nombreuses attaques d’arme au corps à corps ont le désavantage. Les attaques à distance ratent au-delà de leur portée normale et certaines ont le désavantage dans cette portée ; les créatures immergées résistent au feu.', keywords: ['eau', 'nage', 'distance', 'feu'] },
  { id: 'combat-improvised', category: 'Combat', title: 'Arme improvisée', summary: 'Le MJ rapproche l’objet d’une arme existante quand c’est pertinent ; sinon l’attaque inflige typiquement 1d4 du type adapté. La maîtrise ne s’applique que si le personnage est entraîné avec ce type d’arme.', keywords: ['objet', 'improvisée', '1d4'] },

  { id: 'move-split', category: 'Mouvement', title: 'Fractionner son déplacement', summary: 'Tu peux répartir ton déplacement avant et après tes actions, actions bonus et réactions du même tour.', keywords: ['vitesse', 'tour'] },
  { id: 'move-difficult', category: 'Mouvement', title: 'Terrain difficile', summary: 'Chaque mètre parcouru coûte un mètre supplémentaire. Plusieurs causes de terrain difficile sur la même zone ne se cumulent pas.', keywords: ['coût', 'vitesse', 'terrain'] },
  { id: 'move-spaces', category: 'Mouvement', title: 'Traverser les espaces', summary: 'Tu peux traverser un allié, une créature Incapable d’agir, une créature Très Petite ou une créature distante de deux catégories de taille. Tu ne peux généralement pas terminer dans un espace occupé.', keywords: ['taille', 'occupé', 'allié'] },
  { id: 'move-prone', category: 'Mouvement', title: 'À terre et ramper', summary: 'Tu peux te jeter à terre sans action si ta vitesse n’est pas nulle. Te relever coûte la moitié de ta vitesse ; ramper consomme du déplacement supplémentaire.', keywords: ['prone', 'relever', 'ramper'] },
  { id: 'move-long-jump', category: 'Mouvement', title: 'Saut en longueur', summary: 'Avec 3 m d’élan, la distance maximale en pieds égale la Force ; sans élan, elle est divisée par deux. Chaque pied sauté consomme du déplacement. Un atterrissage difficile peut demander Acrobaties DD 10.', keywords: ['saut', 'force', 'acrobaties'] },
  { id: 'move-high-jump', category: 'Mouvement', title: 'Saut en hauteur', summary: 'Avec 3 m d’élan, la hauteur en pieds vaut 3 + modificateur de Force, minimum 0 ; sans élan, elle est divisée par deux. Les bras permettent d’atteindre plus haut que le saut seul.', keywords: ['saut', 'force', 'hauteur'] },
  { id: 'move-climb-swim', category: 'Mouvement', title: 'Grimper et nager', summary: 'Sans vitesse adaptée, chaque distance parcourue coûte du déplacement supplémentaire. Le MJ peut demander Athlétisme lorsque la surface ou le courant rend l’effort incertain.', keywords: ['escalade', 'nage', 'athlétisme'] },
  { id: 'move-fly', category: 'Mouvement', title: 'Voler et tomber', summary: 'Une créature en vol tombe si elle est À terre, Incapable d’agir ou si sa vitesse de vol devient nulle, sauf si elle peut faire du surplace. Une chute consomme instantanément la distance prévue par la règle de chute.', keywords: ['vol', 'chute', 'surplace'] },
  { id: 'move-squeeze', category: 'Mouvement', title: 'Se faufiler', summary: 'Une créature peut traverser un passage prévu pour une taille inférieure d’un cran. Son mouvement y coûte davantage, ses attaques et sauvegardes de Dextérité ont le désavantage, et les attaques contre elle ont l’avantage.', keywords: ['étroit', 'taille', 'passage'] },

  { id: 'explore-light', category: 'Exploration', title: 'Lumière et obscurcissement', summary: 'Une zone légèrement obscurcie désavantage les tests de Perception visuelle. Dans une zone fortement obscurcie, une créature est considérée Aveuglée pour tenter de voir.', keywords: ['vision', 'ténèbres', 'perception'] },
  { id: 'explore-passive', category: 'Exploration', title: 'Perception passive', summary: 'Le MJ peut utiliser une valeur passive pour déterminer ce qui est remarqué sans recherche active. Une recherche volontaire relève de l’action Chercher.', keywords: ['passif', 'piège', 'secret'] },
  { id: 'explore-falling', category: 'Exploration', title: 'Chute', summary: 'Une chute inflige des dégâts selon la distance, avec un plafond, puis laisse normalement la créature À terre. Les capacités qui ralentissent ou annulent la chute s’appliquent avant la résolution finale.', keywords: ['tomber', 'dégâts', 'à terre'] },
  { id: 'explore-suffocation', category: 'Exploration', title: 'Suffocation', summary: 'Une créature peut retenir son souffle pendant une durée liée à sa Constitution ; lorsqu’elle n’a plus d’air, les conséquences s’aggravent rapidement jusqu’à 0 PV.', keywords: ['respiration', 'eau', 'constitution'] },
  { id: 'explore-darkvision', category: 'Exploration', title: 'Vision dans le noir', summary: 'Dans sa portée, elle transforme les ténèbres ordinaires en lumière faible et la lumière faible en lumière vive. Elle ne révèle pas les couleurs dans l’obscurité et ne traverse pas les ténèbres magiques sauf indication.', keywords: ['noir', 'vision', 'ténèbres', 'couleurs'] },
  { id: 'explore-travel', category: 'Exploration', title: 'Voyage et rythme', summary: 'Le rythme choisi arbitre distance, discrétion et vigilance. Un trajet prolongé au-delà de la durée normale appelle des sauvegardes de Constitution de plus en plus difficiles et peut donner de l’Épuisement.', keywords: ['voyage', 'allure', 'marche forcée'] },
  { id: 'explore-food-water', category: 'Exploration', title: 'Eau et nourriture', summary: 'Un manque d’eau devient dangereux plus vite qu’un manque de nourriture. À chaque échéance sans ration suffisante, applique les sauvegardes et niveaux d’Épuisement prévus ; manger et boire suffisamment enclenche la récupération.', keywords: ['faim', 'soif', 'ration', 'épuisement'] },
  { id: 'explore-object', category: 'Exploration', title: 'Endommager un objet', summary: 'Le MJ fixe la CA selon le matériau, les PV selon la taille et la solidité, et peut donner immunités ou seuil de dégâts. Un objet à 0 PV est détruit ou inutilisable selon sa nature.', keywords: ['porte', 'objet', 'matériau', 'seuil'] },

  { id: 'social-attitudes', category: 'Interaction', title: 'Attitudes', summary: 'Une créature peut être amicale, indifférente ou hostile. L’attitude influence le DD et peut donner avantage ou désavantage au test d’influence, mais ne force jamais une demande impossible ou contraire à ses intérêts essentiels.', keywords: ['amical', 'indifférent', 'hostile', 'attitude'] },
  { id: 'social-influence', category: 'Interaction', title: 'Résoudre une influence', summary: 'Le joueur formule clairement sa demande et son approche. Le MJ décide si elle est acceptée, refusée ou incertaine ; dans ce dernier cas, il choisit la compétence sociale et le DD à partir de l’attitude et du risque.', keywords: ['persuasion', 'intimidation', 'tromperie', 'dd'] },
  { id: 'social-deception', category: 'Interaction', title: 'Mensonge et intuition', summary: 'Tromperie mesure la crédibilité du mensonge ; Intuition aide à lire l’état d’esprit et les indices. Un bon résultat ne remplace ni preuve impossible ni contrôle mental.', keywords: ['mensonge', 'intuition', 'tromperie'] },

  { id: 'magic-one-slot', category: 'Magie', title: 'Un emplacement par tour', summary: 'Pendant un même tour, tu ne peux dépenser qu’un seul emplacement pour lancer un sort, même si un second sort utiliserait une action bonus.', keywords: ['emplacement', 'bonus', 'limite'] },
  { id: 'magic-concentration', category: 'Magie', title: 'Concentration', summary: 'Une seule concentration à la fois. Les dégâts appellent une sauvegarde de Constitution DD 10 ou la moitié des dégâts, plafonnée à 30. Être Incapable d’agir ou commencer une autre concentration met fin à la précédente.', keywords: ['constitution', 'dd', 'sort'] },
  { id: 'magic-long-cast', category: 'Magie', title: 'Incantation longue et rituel', summary: 'Pour une incantation d’au moins une minute, prends l’action Magie à chaque tour et maintiens ta concentration. Si elle se rompt, le sort échoue et l’incantation doit recommencer.', keywords: ['rituel', 'minute', 'concentration'] },
  { id: 'magic-components', category: 'Magie', title: 'Composantes', summary: 'Les composantes verbales, somatiques et matérielles doivent être possibles. Un focaliseur peut remplacer une composante matérielle sans coût indiqué et non consommée.', keywords: ['verbal', 'somatique', 'matériel', 'focaliseur'] },
  { id: 'magic-target', category: 'Magie', title: 'Cibles et ligne dégagée', summary: 'Une cible doit respecter la portée et le type demandé par le sort. Pour viser un point, le lanceur doit généralement disposer d’un trajet dégagé ; un obstacle total peut bloquer l’origine ou l’effet.', keywords: ['cible', 'portée', 'ligne', 'obstacle'] },
  { id: 'magic-area', category: 'Magie', title: 'Zones d’effet', summary: 'Cône, cube, cylindre, émanation, ligne et sphère définissent une origine, une taille et les espaces touchés. Une créature est affectée si sa zone est incluse selon la géométrie et les règles de couvert du sort.', keywords: ['cône', 'cube', 'cylindre', 'émanation', 'ligne', 'sphère'] },
  { id: 'magic-ritual', category: 'Magie', title: 'Rituel', summary: 'Un sort portant l’étiquette Rituel peut être lancé en ajoutant 10 minutes sans dépenser d’emplacement, uniquement si la capacité de lancement du personnage autorise ce mode et s’il a accès au sort.', keywords: ['rituel', 'dix minutes', 'emplacement'] },
  { id: 'magic-counter', category: 'Magie', title: 'Interrompre une incantation', summary: 'Une réaction ou capacité ne stoppe un sort que si son déclencheur et sa portée sont respectés. Une incantation longue exige une action Magie et la concentration à chacun des tours jusqu’à son terme.', keywords: ['contrecarrer', 'réaction', 'incantation'] },

  { id: 'health-damage-order', category: 'Santé', title: 'Ordre des dégâts', summary: 'Applique d’abord immunité, puis une seule résistance et une seule vulnérabilité pertinentes. Arrondis chaque division à l’inférieur. Les PV temporaires absorbent ensuite les dégâts avant les PV.', keywords: ['résistance', 'vulnérabilité', 'immunité', 'arrondi'] },
  { id: 'health-healing', category: 'Santé', title: 'Soins', summary: 'Les soins ne dépassent pas le maximum de PV et ne rendent normalement rien à une créature morte. Récupérer au moins 1 PV efface les jets contre la mort et permet de reprendre conscience.', keywords: ['soin', 'maximum', 'conscience'] },
  { id: 'health-instant-death', category: 'Santé', title: 'Mort instantanée', summary: 'Si les dégâts restant après être tombé à 0 égalent ou dépassent le maximum de PV, la créature meurt immédiatement. À 0 PV, de nouveaux dégâts donnent un échec, deux si l’attaque est critique.', keywords: ['mort', 'dégâts massifs', 'zéro'] },
  { id: 'health-stabilize', category: 'Santé', title: 'Stabiliser', summary: 'Un test de Sagesse (Médecine) DD 10 ou un effet adapté peut stabiliser une créature à 0 PV. Elle cesse ses jets contre la mort mais reste Inconsciente jusqu’à recevoir des PV ou se réveiller selon la règle.', keywords: ['médecine', 'stable', 'mort'] },
  { id: 'health-exhaustion', category: 'Santé', title: 'Épuisement', summary: 'Chaque niveau impose −2 à tous les jets de d20 et réduit la vitesse de 1,50 m. À six niveaux, la créature meurt. Un repos long réussi retire normalement un niveau.', keywords: ['malus', 'vitesse', 'mort', 'repos'] },

  { id: 'rest-short', category: 'Repos et survie', title: 'Repos court', summary: 'Une heure de récupération permet de dépenser des dés de vie et de recharger les capacités qui le précisent. Initiative, sort autre qu’un sort mineur ou dégâts interrompent le repos sans bénéfice.', keywords: ['dé de vie', 'heure', 'récupération'] },
  { id: 'rest-long', category: 'Repos et survie', title: 'Repos long', summary: 'Au moins huit heures, dont au moins six de sommeil pour la plupart des personnages. Il restaure tous les PV et dés de vie dépensés, réduit l’épuisement de 1 et recharge les ressources indiquées. Il exige au moins 1 PV au départ.', keywords: ['sommeil', 'huit heures', 'récupération'] },
  { id: 'hp-temporary', category: 'Repos et survie', title: 'PV temporaires', summary: 'Ils absorbent les dégâts avant les PV, ne se cumulent pas et ne soignent pas. Si une nouvelle source en donne, la créature choisit de garder l’ancienne valeur ou d’adopter la nouvelle.', keywords: ['temporaire', 'dégâts', 'choix'] },
  { id: 'hp-zero', category: 'Repos et survie', title: 'À 0 PV', summary: 'Un personnage tombe Inconscient et effectue des jets contre la mort. Trois succès stabilisent, trois échecs tuent ; un 1 naturel compte double et un 20 naturel rend 1 PV. Les dégâts reçus ajoutent des échecs.', keywords: ['mort', 'stabilisé', 'inconscient'] },
  { id: 'heroic-inspiration', category: 'Repos et survie', title: 'Inspiration héroïque', summary: 'Dépense-la juste après avoir lancé n’importe quel dé pour le relancer, en gardant le nouveau résultat. Si tu en gagnes alors que tu l’as déjà, tu peux la transmettre à un autre personnage joueur qui n’en a pas.', keywords: ['relance', 'dé', 'transmettre'] },
];
